version: '3.8'

services:
  app:
    build: .
    container_name: emarecripto
    ports:
      - "8300:8300"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
